name: CPU TESTS ALL

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: read

jobs:
  docker_build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Docker Layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker Image w/ Cache
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: cuda-qcb:latest
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        outputs: type=docker

    - name: Move Cache
      if: success()
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Run All Tests & Generate Report
      run: |
        docker run --platform linux/amd64 -i --rm \
          -v ${{ github.workspace }}:/src \
          -w /src/tests/fastx \
          cuda-qcb:latest \
          bash -c "make clean && make && ./obj/all_tests --gtest_output=xml:report.xml"

    - name: Upload FASTX GTEST XML Report
      uses: actions/upload-artifact@v4
      with:
        name: gtest-report
        path: tests/fastx/report.xml

    - name: Publish FASTX GTEST XML Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: tests/fastx/report.xml
        check_name: "FASTX Test Results (CPU)"