name: All CPU & GPU Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: read

jobs:
  BUILD_DOCKER_IMAGE_AND_RUN_TESTS:
    runs-on: ubuntu-latest

    steps:
    - name: FREE DISK SPACE
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: CHECKOUT CODE
      uses: actions/checkout@v3

    - name: DOCKER BUILDX
      uses: docker/setup-buildx-action@v3

    - name: USE GITHUB DOCKER CONTAINER REGISTRY
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: CACHE DOCKER LAYERS
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: BUILD DOCKER IMAGE WITH CACHE
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: cuda-qcb:latest
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        outputs: type=docker

    - name: MOVE CACHE
      if: success()
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: RUN ALL TESTS AND GENERATE REPORT
      run: |
        docker run --platform linux/amd64 -i --rm \
          -v ${{ github.workspace }}:/src \
          -w /src/tests/cpu \
          cuda-qcb:latest \
          bash -c "make clean && make all && ./obj/all_cpu_tests --gtest_output=xml:all_cpu_report.xml"

    - name: UPLOAD ALL TEST RESULTS
      uses: actions/upload-artifact@v4
      with:
        name: gtest-report
        path: tests/cpu/all_cpu_report.xml

    - name: PUBLISH ALL TEST RESULTS
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          tests/cpu/all_cpu_report.xml 
          tests/gpu/outfiles/all_gpu_report.xml
        check_name: "CPU & GPU TEST RESULTS"